title: Title
author: Names
# logo: figures/your_logo.png   # optioneel

execute:
  execute_notebooks: "auto"

only_build_toc_files: true

html:
  favicon: "figures/favicon.ico"
  baseurl: ""   

sphinx:
  config:
    # LIST THE NOTEBOOKS YOU WANT TO EXECUTE DURING BUILD
    nb_execution_includepatterns:
      - "notebooks/intro.ipynb"
      - "notebooks/chapter1.ipynb"
      - "notebooks/chapter2.ipynb"
      - "notebooks/chapter3.ipynb"
      - "notebooks/chapter4.ipynb"
      - "notebooks/chapter5.ipynb"

    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]

    html_theme_options:
      repository_url: "https://github.com/<your-username>/<your-repo>"
      use_repository_button: true
      use_issues_button: true

      launch_buttons:
        thebe: true

    html_last_updated_fmt: '%B %-d, %Y'
    html_show_copyright: false

  extra_extensions:
    - teachbooks_favourites
    - sphinx_tudelft_theme
    - sphinx_nb_execution_patterns

bibtex_bibfiles:
  - references.bib

