title: RWA breakdown
author: Aadi, Jochem, Raul, Victor

execute:
  execute_notebooks: "auto"

repository:
  url: "https://github.com/jjhvandervliet/test_project"
  branch: "main"
  path_to_book: "book/"

html:
  favicon: "figures/favicon.ico"
  baseurl: ""
  use_edit_page_button: true
  use_repository_button: true
  extra_navbar: ""
  theme: sphinx_book_theme

sphinx:
  config:
    extensions:
      - sphinxcontrib.bibtex
      - sphinx_thebe

    bibtex_bibfiles:
      - references.bib

    nb_execution_includepatterns:
      - "notebooks/*.ipynb"

    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

    thebe_config:
      use_thebe_lite: false
      exclude_patterns: ["**/_*.yml"]  # removed "*.md" and "*.ipynb" to allow Thebe

    html_theme_options:
      repository_url: "https://github.com/jjhvandervliet/test_project"
      use_repository_button: true
      use_issues_button: true
      launch_buttons:
        thebe: true
        binderhub_url: "https://mybinder.org"

    html_last_updated_fmt: "%B %-d, %Y"
    html_show_copyright: false

  extra_extensions:
    - teachbooks_favourites
    - sphinx_tudelft_theme
    - sphinx_nb_execution_patterns

parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence
    - deflist
    - html_admonition
    - html_image
    - linkify
  myst_dmath_double_inline: false

      
  
